###############################################################################

# Decide if we need to include the sys makefile
SYS_SRC = $(SYS_PATH)/src
SYS_INC = $(SYS_PATH)/inc
INC_PATH += -I $(SYS_INC)
VPATH += $(SYS_SRC) $(SYS_INC)
# ifeq ($(USE_SYS), TRUE)
include $(SYS_SRC)/Makefile.include
# endif

###############################################################################

