# Append to the files to compile
SRC_FILES += CircularBuffer.cpp Queue.cpp CriticalSection.cpp Mutex.cpp \
             MutexRecursive.cpp SemaphoreBinary.cpp SemaphoreCounting.cpp \
             Scheduler.cpp Task.cpp
