# Project name and files to compile
PROJECT_NAME  = tickless-cc2538
PROJECT_FILES = main.cpp cc2538_lowpower.c
PROJECT_DIR   = .

# Location of the root directory
PROJECT_HOME = ../..

# Include the current path
INC_PATH += -I $(PROJECT_DIR)

# Configure compiling
USE_DRIVER_TPS62730 = TRUE

# Include the Makefile in the root directory
include $(PROJECT_HOME)/Makefile.include
